### ISSUE TITLE
Module not found: Error: Can't resolve 'node-zlib-backport'

### ISSUE THREAD

**Issue by johnsken-jerry** [techiediaries/ngx-qrcode#25]
**Version**
0.0.8

**Environment**
angular 5.0.0
webpack-cli 3.0.8

> I'm using ngx-qrcode2. When I compile Webpack, I have the following warning.

```
WARNING in ./node_modules/qrcode/node_modules/pngjs/lib/parser-sync.js
Module not found: Error: Can't resolve 'node-zlib-backport' in '/Users/lx/workspace/web/node_modules/qrcode/node_modules/pngjs/lib'
 @ ./node_modules/qrcode/node_modules/pngjs/lib/parser-sync.js 8:11-40
 @ ./node_modules/qrcode/node_modules/pngjs/lib/png-sync.js
 @ ./node_modules/qrcode/node_modules/pngjs/lib/png.js
 @ ./node_modules/qrcode/lib/renderer/png.js
 @ ./node_modules/qrcode/lib/server.js
 @ ./node_modules/qrcode/lib/index.js
 @ ./node_modules/ngx-qrcode2/index.js
 @ ./dist/server/main.js
 @ ./server.ts
```

**Comment by johnsken-jerry** [comment]
I found the reason, because the problems caused by the `pngjs version`.

After trying to upgrade pngjs to the latest version, I succeeded in `webpack` compiling it.

`pngjs upgrade latest`

Now pngjs version is 3.3.3

**Comment by rafa-as** [comment]
@techiediaries do you accept PR? Tell me in case of affirmative answer, because I have this same issue  and I've been waiting a long time for a release also upgrading to Angular 7 and some other stuff like https://github.com/techiediaries/ngx-qrcode/issues/29

Can you give us some feedback. We can work on it if you accept the PR and release.
